### ISSUE TITLE
Release for symfony 4

### ISSUE THREAD

**Issue by artggd** [Bee-Lab/BeelabUserPasswordBundle#3]
Hey guys,

I'm going to need this bundle on a Symfony 4 application. I noticed you updated it in a recent [commit](https://github.com/Bee-Lab/BeelabUserPasswordBundle/commit/d0e756d21304bbc9f7827436240084f9d733c7a2), could you please produce a release of this commit soon?

Great job with your set of bundles BTW, simple and useful 👍

**Comment by garak** [comment]
It needs a bit of rework, to adapt current named services to FCQN services

**Comment by artggd** [comment]
I don't think FQCN is necessary, you'd have to alias all your services or face a BC break monster. Also, services declaration apparently hasn't changed for bundles (see [best practices](https://symfony.com/doc/current/bundles/best_practices.html#services)). I wouldn't bother switching 🙂

I'm happy to help you out if you need a hand for polishing things up!

**Comment by garak** [comment]
Sorry, I was wrong: I was thinking this was BeelabUserBundle.
Well, likely there's no big problems allowing Symfony 4 here, but problems I mentioned above are present in BeelabUserBundle.
BC is not a problem, we can release a new major. But we need to make BeelabUserBundle really Symfony4-compatible

**Comment by garak** [comment]
This should be fixed with latest releases of BeelabUserBundle and BeelabUserPasswordBundle
